### ISSUE TITLE
Fail to "return False" in CNLS class

### ISSUE THREAD

**Issue by ds2010** [ds2010/StoNED-Python#17]
Hi @JulianATA, 

It seems there is a return error in the [CNLS](https://github.com/ds2010/StoNED-Python/blob/master/pystoned/CNLS.py) class. When we use the local solver to estimate the multiplicative model, the Class should print `"Estimating the multiplicative model will be available in near future."` and `return False`. But actually, the class first prints the warning and then continues to calculate the model (perhaps using the remote solver). Finally, we can obtain the model estimates. Please see the following example:

    from pystoned import StoNED
    import pandas as pd
    import numpy as np
    # import Finnish electricity distribution firms data 
    url = 'https://raw.githubusercontent.com/ds2010/pyStoNED-Tutorials/master/Data/firms.csv'  
    df = pd.read_csv(url, error_bad_lines=False)
    
    # output (total cost)
    y  = df['TOTEX']
    
    # inputs 
    x1  = df['Energy']
    x1  = np.asmatrix(x1).T
    x2  = df['Length']
    x2  = np.asmatrix(x2).T
    x3  = df['Customers']
    x3  = np.asmatrix(x3).T
    x   = np.concatenate((x1, x2, x3), axis=1)

## using local solver (suppose we have one)
    # build and optimize
    instance = StoNED.StoNED(y, x, z=None, cet = "mult", fun = "cost", rts = "crs")
    instance.optimize(remote=True)
    print(instance.get_technical_inefficiency(method='QLE'))

## using remote solver
    # build and optimize
    instance = StoNED.StoNED(y, x, z=None, cet = "mult", fun = "cost", rts = "crs")
    instance.optimize(remote=False)
    print(instance.get_technical_inefficiency(method='QLE'))

If I understand correctly, when choosing the `remote=False`,  the class should print the warning and return False. So, I think we have to fix it.

**Comment by JulianATA** [comment]
@ds2010 ,here is same explain of the problem.
The reason is `get_technical_inefficiency()`.
For all the `get_something`/`display_something`, the method will first:
- Check if the model optimized
    - If optimized, return the required values.
    - if not, optimize the model remotely and return the required values.

This feature is designed for users forget to optimize the model.
Maybe we can changed it to `if not, print the not optimized warning`.

**Comment by ds2010** [comment]
OK, now I see. I agree that it would better to use  `if not, print the not optimized warning`.
